# This is a basic workflow to help you get started with Actions

name: BumpVersion

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Bump version number
        run:  expr `cat version.txt 2>/dev/null` + 1 >version.txt
      - name: Commit changes
        run: git commit -am "Automatically bump version number"
      - name: Push
        run: git push
